services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: msvc_users
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: msvc_courses
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always

  msvc-users:
    container_name: msvc-users
    image: users:latest
    ports:
      - "8001:8001"
    depends_on:
      - "mysql8"
    restart: always

  msvc-courses:
    container_name: msvc-courses
    image: courses:latest
    ports:
      - "8002:8002"
    depends_on:
      - "postgres14"
    restart: always

volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres



    